language: python
arch: arm64
python: 3.8
env:
  global:
    - MAX_JOBS=2

    - USE_CUDA=0
    - USE_MKLDNN=0
    - USE_DISTRIBUTED=0
    - BUILD_TEST=0
    - USE_SYSTEM_NCCL=0
    - USE_NCC=OFF
    - VERBOSE=1
    - USE_OPENMP=1
before_install:
  # - sudo apt-get -y install python-numpy python-yaml python-cffi python-setuptools python-wheel cmake
  - git clone https://github.com/pytorch/pytorch --recursive
  - cd pytorch

  - git checkout v1.4.0
  - git submodule sync
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt
  - python setup.py bdist_wheel
